# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.IntegerField(choices=[(1, 'admin'), (0, 'regular')], default=0, max_length=100)),
            ],
        ),
    ]
